package Model;
// Generated 25 Feb 2016 5:52:23 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrator generated by hbm2java
 */
@Entity
@Table(name="administrator"
    ,catalog="churchdb"
)
public class Administrator  implements java.io.Serializable {


     private int administratorId;
     private String name;
     private String address;
     private Integer contact;
     private String email;

    public Administrator() {
    }

	
    public Administrator(int administratorId) {
        this.administratorId = administratorId;
    }
    public Administrator(int administratorId, String name, String address, Integer contact, String email) {
       this.administratorId = administratorId;
       this.name = name;
       this.address = address;
       this.contact = contact;
       this.email = email;
    }
   
     @Id 

    
    @Column(name="AdministratorID", unique=true, nullable=false)
    public int getAdministratorId() {
        return this.administratorId;
    }
    
    public void setAdministratorId(int administratorId) {
        this.administratorId = administratorId;
    }

    
    @Column(name="Name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="Contact")
    public Integer getContact() {
        return this.contact;
    }
    
    public void setContact(Integer contact) {
        this.contact = contact;
    }

    
    @Column(name="Email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


