package Model;
// Generated 25 Feb 2016 5:52:23 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name="member"
    ,catalog="churchdb"
)
public class Member  implements java.io.Serializable {


     private int memberId;
     private String name;
     private String address;
     private String email;
     private Integer contact;

    public Member() {
    }

	
    public Member(int memberId) {
        this.memberId = memberId;
    }
    public Member(int memberId, String name, String address, String email, Integer contact) {
       this.memberId = memberId;
       this.name = name;
       this.address = address;
       this.email = email;
       this.contact = contact;
    }
   
     @Id 

    
    @Column(name="MemberID", unique=true, nullable=false)
    public int getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }

    
    @Column(name="Name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="Email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Contact")
    public Integer getContact() {
        return this.contact;
    }
    
    public void setContact(Integer contact) {
        this.contact = contact;
    }




}


