package Model;
// Generated 25 Feb 2016 5:52:23 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PerformanceAssessment generated by hbm2java
 */
@Entity
@Table(name="performance_assessment"
    ,catalog="churchdb"
)
public class PerformanceAssessment  implements java.io.Serializable {


     private String name;
     private String email;
     private Integer contact;

    public PerformanceAssessment() {
    }

	
    public PerformanceAssessment(String name) {
        this.name = name;
    }
    public PerformanceAssessment(String name, String email, Integer contact) {
       this.name = name;
       this.email = email;
       this.contact = contact;
    }
   
     @Id 

    
    @Column(name="Name", unique=true, nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Contact")
    public Integer getContact() {
        return this.contact;
    }
    
    public void setContact(Integer contact) {
        this.contact = contact;
    }




}


