package Model;
// Generated 25 Feb 2016 5:52:23 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrayerRequest generated by hbm2java
 */
@Entity
@Table(name="prayer_request"
    ,catalog="churchdb"
)
public class PrayerRequest  implements java.io.Serializable {


     private int memberId;
     private String name;
     private String category;
     private String description;
     private Date date;

    public PrayerRequest() {
    }

	
    public PrayerRequest(int memberId) {
        this.memberId = memberId;
    }
    public PrayerRequest(int memberId, String name, String category, String description, Date date) {
       this.memberId = memberId;
       this.name = name;
       this.category = category;
       this.description = description;
       this.date = date;
    }
   
     @Id 

    
    @Column(name="MemberID", unique=true, nullable=false)
    public int getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }

    
    @Column(name="Name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Category", length=45)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="Description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


