package Model;
// Generated 25 Feb 2016 5:52:23 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tithe generated by hbm2java
 */
@Entity
@Table(name="tithe"
    ,catalog="churchdb"
)
public class Tithe  implements java.io.Serializable {


     private String name;
     private String address;
     private Date date;
     private Double amount;

    public Tithe() {
    }

	
    public Tithe(String name) {
        this.name = name;
    }
    public Tithe(String name, String address, Date date, Double amount) {
       this.name = name;
       this.address = address;
       this.date = date;
       this.amount = amount;
    }
   
     @Id 

    
    @Column(name="Name", unique=true, nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="Amount", precision=22, scale=0)
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }




}


